### ISSUE TITLE
Crash when loading visual studio solution that uses custom macros from a properties file

### ISSUE THREAD

**Issue by iauns** [CoatiSoftware/CoatiBugTracker#107]
I've attached a small working example demonstrating a coati crash when opening a visual studio project. I also noticed that coati may not be interpreting some environment variables that VS sets itself. For example, $(ProjectDir).

[coati-crash-vs-06-25-2016.zip](https://github.com/CoatiSoftware/CoatiBugTracker/files/333334/coati-crash-vs-06-25-2016.zip)

(edit: this is against Coati 0.7 on Windows 10)

**Comment by wrongway88** [comment]
Thanks for your report iauns. I'm able to recreate the crash with your sample, I'll let you know as soon as it is fixed.

As for the VS variable, right now we are only supporting a few of them:

- SolutionPath
- SolutionDir
- SolutionName
- SolutionFileName

Some more will be included in the next update:

- ProjectFileName
- ProjectName
- ProjectExt
- ProjectDir
- ProjectPath

There is however going to be a major overhaul of how we create coati projects from VS solutions in the (near-ish) future. So expect those issues to be resolved later down the line.

**Comment by wrongway88** [comment]
We have added a new feature to the plugin that creates a compilation database from VS solutions. Solution parsing is now handled within VS through the plugin, resolving macros shouldn't be an issue anymore.

Note that the CDB creation feature is still in it's testing phase, therefore the old solution parsing feature is still available. CDB have to be loaded manually into Coati as of now. This will be automated in the future.
