### ISSUE TITLE
Errors on Windows due to _NOEXCEPT

### ISSUE THREAD

**Issue by mkurdej** [CoatiSoftware/CoatiBugTracker#111]
I've tried Coati with this project: https://github.com/bblanchon/ArduinoJson (from a VS solution generated with CMake).
There are quite a few errors due to `_NOEXCEPT` macro (probably being undefined): `Error: expected function body after function declarator`.

So, I've added `-D _NOEXCEPT=noexcept` (and tried `-D _NOEXCEPT=` as well) to the compiler flags, but it doesn't change anything (a bug here?).

**Comment by mlangkabel** [comment]
Thanks for reporting this one @mkurdej. 

Adding a -D flag to add a define already works in the current release (0.7) of Coati. We will look into this to figure out what is really happening here.

Regarding those errors: Coati distinguishes between `Errors` and `Fatal Errors`. Simple `Errors` just have a very local effect on the index Coati builds. So usually you can just ignore them.

**Comment by mkurdej** [comment]
Yes, I can indeed ignore them, but that makes lots of false positives that make the exploration hindered.
Just to be clear, I use Coati 0.7.0.0 on Windows 10.
Thanks for looking into it!

**Comment by mlangkabel** [comment]
Hi @mkurdej, We just re-evaluated this issue with our latest build (Coati 0.10.0) and the new version of our Visual Studio plugin. The plugin now just converts the VS project to a Compilation Database (CDB) that knows all the include paths and compile flags Visual Studio uses. 
After creating a new Coatiproject that imports the CDB we had no errors at all while indexing the project and the indexed data looks reasonable :)
