### ISSUE TITLE
Feature request: move Preferences to Edit menu

### ISSUE THREAD

**Issue by mkurdej** [CoatiSoftware/CoatiBugTracker#113]
It seems a bit unexpected and counter-intuitive that Preferences menu is hidden under Help, and not under Edit (or Project alternatively).
IMO, putting it into Edit is more standard on Unix-like systems, and putting it to File/Project is rather Windows-like.

**Comment by egraether** [comment]
Fixed with 0.7.1.2
Moved Preferences to Edit menu. On MacOS they stay in the Application menu.
