### ISSUE TITLE
Create project from VS solution misses includes

### ISSUE THREAD

**Issue by mlangkabel** [CoatiSoftware/CoatiBugTracker#115]
When automatically creating a coatiproject from the VS solution that ships with the nana project (https://github.com/cnjinhao/nana) Coati misses the General Include Directories specified in the "VC++ Directories" tab of the project's "Configuration Properties".

**Comment by wrongway88** [comment]
Should work now with the VS CDB creation. Please verify.

**Comment by mlangkabel** [comment]
I just tested this. It's fixed :)
