### ISSUE TITLE
Prefill indexed include paths list when creating Coatiproject from CDB

### ISSUE THREAD

**Issue by mlangkabel** [CoatiSoftware/CoatiBugTracker#119]
All include paths a project needs to build are already specified in the projects CDB. Therefore we should use these paths to prefill the list of indexed include paths when creating a Coatiproject from CDB. With this approach the user can opt out of some folders (like external packages) by removing entries from this list.

Initially the list should add all the paths that a) are specified by the CDB *and* b) can be found by Coati in the environment. This should provide a lot more feedback on if there is anything going wrong.

**Comment by brucestephens** [comment]
Arguably, the note inside [Indexing Clang with Coati using Clang](https://www.coati.io/blog/indexing_clang_with_coati_using_clang/) about using compilation databases makes this a bug rather than a feature (and presumably a bug that's been resolved in the code).

**Comment by egraether** [comment]
A prefilling method was added with 0.7.1.79
