### ISSUE TITLE
Coati Trial error on Windows: Warn user if Visual C++ 2015 Redistributable is not installed

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#123]
Error dialog shows when running after installation:
![image001](https://cloud.githubusercontent.com/assets/201867/17276034/8a3f0094-571c-11e6-9783-f32d913515fb.png)
Reportet on Windows 7 with SP1 for “Coati_Trial_0_7_0_22"

Also the name of the shortcut seems wrong: ”Coati Trail” instead of “Coati trial”.

**Comment by mlangkabel** [comment]
My guess is that your install of the Microsoft Visual C++ 2015 Redistributable (32 bit) may be corrupted. Please try to resintall and start Coati again.

**Comment by rubenpenalva** [comment]
Installing the vs2015 runtime solved the issue. I actually didn't have it installed.

**Comment by mlangkabel** [comment]
* fixed start menu entry in Coati 0.7.1.81
* we'll add the redistributable as prerequisit to the new Coati installer that will ship with our next release.
