### ISSUE TITLE
Add support for excluding files from a project

### ISSUE THREAD

**Issue by dhallas** [CoatiSoftware/CoatiBugTracker#125]
When creating an empty project and adding folders to it, Coati picks up all files in those folders, it would be really nice if you could specify a list of files to be excluded. This way you could add your top level directory and than exclude any not used/example files etc.

**Comment by egraether** [comment]
@dhallas This was already implemented with #68, but is a little hidden.

You can find the "Exclude Paths" setting in the Advanced Settings of the Edit Project dialog found in the menu at "Project -> Edit Project": https://www.coati.io/documentation/#EditProjectWindow
