### ISSUE TITLE
Consolidate anonymous namespaces

### ISSUE THREAD

**Issue by dhallas** [CoatiSoftware/CoatiBugTracker#126]
It would be really helpful to have an option to consolidate anonymous namespaces, or a way to hide them. Some codebases use them a lot so they completely fill up the namespace view

**Comment by mlangkabel** [comment]
Hi @dhallas, what do you mean by "namespace view"? Do you mean the view you get when being in the overview state and you click the namespace bundle node?

**Comment by dhallas** [comment]
Yes, this was actually the "view" I was referring to. Currently I am using Coati on a codebase with 1200+ unnamed namespaces, so it makes this view rather useless. Maybe unnamed namespaces could be represented with a single item in this view, and navigating to that would expand to all the individual unnamed namespaces? Basically adding a single indirection to navigate them. Maybe have a count or something on the top level item?

**Comment by mlangkabel** [comment]
I think that's a good idea. Thanks for your feedback!

**Comment by egraether** [comment]
Fixed with 0.7.1.17
Added sub-bundle for anonymous namespaces to namespaces bundle
