### ISSUE TITLE
Crash when loading Project from Visual Studio Solution

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#127]
New Project -> Create from VS Solution -> Choose Solution Dialog -> ‘Open’ -> crash

Dump available

**Comment by wrongway88** [comment]
The VS solution parsing feature will be retired sometime soon. Instead the VS plugin will create a compilation database which is to be used in Coati. Solution parsing will happen within VS, which resolves many issues and should make it much more robust.

The new feature is already available in the latest VS plugin version for testing purposes. It would be great if you could try the new CDB creation feature to index your solution in Coati.

Note that the new feature is not yet fully integrated, the created CDBs won't be loaded into coati automatically. This will be added in the future. Please refer to the documentation for details.

**Comment by degracode** [comment]
Great, thanks. Would it be possible to get a new evaluation license to test this?

**Comment by egraether** [comment]
@degracode You will receive a new test license in a moment.

**Comment by degracode** [comment]
Thanks. I downloaded the latest version (0.9.0) and followed the instructions to update the VSIX plugin, then completed the Create Compilation Database dialog; after hitting ‘Create’, a dialog popped up briefly with “Waiting…”, and then disappeared. I can’t see the database file on-disk anywhere, and the only new file is, Project.VC.VC.opendb, which is less than 1KB in size.
 
I’ve tried a few different project selections (all, a couple, one small project) with no change in results, except for the “Waiting…” dialog taking longer to disappear.

***********

This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.

**Comment by wrongway88** [comment]
Thanks for the quick feedback @degracode. Is the solution you are using available, or can you provide a version that recreates the bug?

I wonder if there is anything notable about your solution that would cause the creation process to end prematurely. What kinds of projects are in the solution (C/C++, C#, VB...), does it have a complex structure (with projects in folders...)?
Also, which VS version are you using? (2012, 2013, 2015... Professional, Community...)

**Comment by degracode** [comment]
We're using VS 2015. Our solution is all C++, and contains 17 projects, divided into 3 top-level folders (Libraries, ThirdPartyLibraries, Tests) and 3 executable projects in the root. On-disk, the projects are in a similar layout.
I can't release our solution to you sadly, but I will try and narrow down the bug by building something similar.
Does the plugin generate any logging I can pass on?

**Comment by wrongway88** [comment]
From your description I couldn't make out anything that should cause issues. A solution that recreates the bug would be a great help, I appreciate the effort @degracode 
Unfortunately the plugin does not (yet) create logs.

**Comment by wrongway88** [comment]
@degracode 
A new version of the plugin was included in last week's update (Coati 0.9.23 - https://www.coati.io/downloads).
I was hoping you could try again with this version. Error and exception handling was improved, so maybe the issue is resolved.

If not, optional file logging is now included. You can turn it on in Tools->Options->Coati. The logs are stored in .../AppData/Local/Coati Software/Plugins/VS. You can also turn on log obfuscation, which will replace any file or project names, as well as directories, within the log files with alphanumeric strings.
If the problem still exists, could you send me the log file?

**Comment by egraether** [comment]
The Visual Studio solution loading is now handled within the Visual Studio plugin. No reaction from user in 3 months. Closing now.
