### ISSUE TITLE
Crash on Arch Linux 64bit, kernel 4.2.5

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#13]
output:
$ ./Coati.sh
/path-to-coati/coati
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by egraether** [comment]
The issue should be fixed with the Linux 64bit version of the new Coati Release v0.4

**Comment by egraether** [comment]
Closing due to one month without reply.

**Comment by jcelerier** [comment]
hi, I'm getting the same error on my software (": CommandLine Error: Option 'help-list' registered more than once!"), do you remember how you solved this ?

 thanks.
