### ISSUE TITLE
Top entry field should enable tabbing through name spaces

### ISSUE THREAD

**Issue by HarryDC** [CoatiSoftware/CoatiBugTracker#133]
When entering a type in the edit field it always fills with the next best complete type, ie. it goes from, `NamespaceA::Namesp` to `NamespaceA::NamespaceB::ClassName`, we have a fairly large namespace hierarchy and it would be much more convenient to be able to tab through the namespaces up to the double colon. i.e. from `Name` `<tab>` to  `NamespaceA::` `<tab>` to `NamespaceA::NamespaceB::` and so forth.

In the reverse it might  helpful to be able to navigate backwards in a similar way i.e. on delete don't delete the complete typename but only up to the preceding double colon. E.g. From `NamespaceA::NamespaceB::ClassName` via `<del>` to `NamespaceA::NamespaceB::`

**Comment by egraether** [comment]
Fixed with 0.7.1.18
Thanks for the suggestion, I like it a lot! Implemented as proposed.
