### ISSUE TITLE
Coati crashes on Debian Jessie

### ISSUE THREAD

**Issue by elektm93** [CoatiSoftware/CoatiBugTracker#14]
Coati Version 0.3.0 for Linux

OS: Debian 8.2 jessie
Kernel: x86_64 Linux 4.2.0-1-amd64

when executing in the command line, following error occours
```bash
./Coati.sh 
Segmentation fault
```

tried to backtrack the error, but debugsymbols are, certainly, turned off. Could backtrack it to 

```bash
exec $COATI_PATH/Coati
```

**Comment by egraether** [comment]
Our build for Linux 64bit is currently done on Arch Linux. It's not fully downward compatible to older kernels, I suspect that's the problem here. We are currently working on building our Linux 64bit version on an older system. I will let you know.

**Comment by egraether** [comment]
Please test the Linux 64bit version of the new Coati Release v0.4 and let us know if your problem persists.

**Comment by egraether** [comment]
Closing due to one month without reply.
