### ISSUE TITLE
Crash when indexing assert.h

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#146]
20:45:43 | INFO: file: xxxxx.cpp < 0:0 0:0>
20:45:46 | INFO: macro use: assert <xxxxx.cpp 66:3 66:8>
20:45:46 | INFO: macro use: __ASSERT_VOID_CAST </usr/include/assert.h 50:25 50:42>
20:45:47 | CxxTypeNameResolver.cpp:202 typeToDataType() | INFO: Unhandled kind of type encountered: FunctionProto

The range 66:3-66:8 is assert:

  assert(strId.size() == 8);

And the offending line in asser.h:
# define assert(expr)>> (__ASSERT_VOID_CAST (0))

**Comment by mlangkabel** [comment]
cannot reproduce this on windows

**Comment by egraether** [comment]
Definitely fixed with 0.9.78
Tested all std headers on all platforms and fixed all crashes.
