### ISSUE TITLE
Visual Studio Solution/Project parsing

### ISSUE THREAD

**Issue by ChriZzZ** [CoatiSoftware/CoatiBugTracker#15]
loading a coati project based on a .sln or .vcxproj file would be nice

**Comment by wrongway88** [comment]
Agreed, feature is in the making and might be part of the next release.

**Comment by jaked122** [comment]
Would it be possible to add additional project file definitions, like CMake?

**Comment by mlangkabel** [comment]
@jaked122: we are already implementing support for CMake files via compilation databases (which can be generated by CMake). The feature didn't make it into our initial release but expect to hear more of it soon! 
Lets open a new feature for that: #35
