### ISSUE TITLE
Tooltips unreadable in dark scheme

### ISSUE THREAD

**Issue by pwinter1991** [CoatiSoftware/CoatiBugTracker#16]
![coati-tooltip](https://cloud.githubusercontent.com/assets/5417215/11727950/4946830c-9f87-11e5-9ad3-6cc0838855f8.png)

**Comment by egraether** [comment]
Can't reproduce on Mac. What platform are you using?

**Comment by pwinter1991** [comment]
Probably a windows only thing. I tested it on Win8.1 and Win10.

**Comment by mlangkabel** [comment]
I can reproduce it on Windows 7. So the chances are good that it will be fixed in the next release :)

**Comment by egraether** [comment]
Fixed with 0.3.0.52
Apparently the tooltip background color can't be changed for Windows. We are using bright tooltips in every color scheme now.
