### ISSUE TITLE
Right-click on graph elements does same as left-click

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#160]

**Comment by egraether** [comment]
Could not reproduce on Mac

**Comment by mlangkabel** [comment]
Could not reproduce on Windows 7. Right-click on graph element opens the context menu that displays the options "back" and "forward".

**Comment by egraether** [comment]
Reported on Windows 10 actually

**Comment by st4ll1** [comment]
Could not reproduce on Windows 10 and Coati 0.10 either.
