### ISSUE TITLE
Global includes not detected with newer Visual Studio

### ISSUE THREAD

**Issue by Mike4Online** [CoatiSoftware/CoatiBugTracker#169]
Visual Studio 2010 and newer versions specify global (per-user) include folders via the files %LOCALAPPDATA%\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props and %LOCALAPPDATA%\Microsoft\MSBuild\v4.0\Microsoft.Cpp.x64.user.props.

But Coati ignores any include folders specified in these files when importing a Visual Studio solution file or when clicking the Detect button.  

I am using Coati 0.7.0.22 on Windows.

**Comment by mlangkabel** [comment]
Right now we are implementing a new version of the visual studio plugin, which will be responsible for converting a VS project to something Coati can work with. This plugin will add the include folders specified in those files to the Coati project.

I think keeping these settings per project is a cleaner solution compared to setting them as global include paths used for all projects. This way you may use Coati on non-Visual Studio projects without having to worry about some include paths set for your Visual Studio projects.

**Comment by Mike4Online** [comment]
>> I think keeping these settings per project is a cleaner solution
compared to setting them as global include paths used for all projects.

Keeping them per project also lets you override the "global" Visual Studio
includes for a specific project.  But if the user ever changes their global
include folder paths in Visual Studio, they should be able to make a
corresponding change in Coati.  Otherwise, they have to manually update
every Coati project (at least the ones that have corresponding Visual
Studio projects) to adjust the "global" include paths in Coati.

There are many ways a Visual Studio project can specify include folders.
The MSBuild props files I mentioned are per-user files, but there are also
per-computer props files (in folder *C:\Program Files
(x86)\MSBuild\Microsoft.Cpp\v4.0*).  These per-computer files point to the
VC/include and atlmfc include folders in the Visual Studio Program Files
(x86) folder.  There are props for Unicode projects and props for VC++
projects imported from older Visual Studio versions, too.  Users can add
custom props files containing other include paths, and share these custom
props files among several VC++ projects.   See this article
<https://manski.net/2012/01/sharing-project-properties-in-visual-c/> and this
article
<https://blogs.msdn.microsoft.com/vsproject/2009/06/23/inherited-properties-and-property-sheets/>
for details regarding the "property sheets" (props files) used by Visual
Studio 2010 and newer.

Each Visual Studio VC++ project file can specify "additional include folders
<http://stackoverflow.com/questions/1460798/is-there-a-list-of-visual-studio-environment-variables/12056067#12056067>"
which should be taken into account as well.  Also, the VC++ project files
can specify props files only for specific build configurations or specific
source files, so it can get very complex (see this article
<https://blogs.msdn.microsoft.com/visualstudio/2010/05/14/a-guide-to-vcxproj-and-props-file-structure/>).
And the command-line VC++ compiler can get include paths from the INCLUDE
environment variable.

The include paths in props files and vcxproj files can contain Visual
Studio "macros", inheritance and relative paths, so it can be difficult to
know precisely which include folders are in effect.  The Visual Studio API
(object model) probably has a way to interpret these values for you.

I think the best way would be to let Visual Studio track the include
folders for you.  In other words, have a checkbox within Coati Project
Properties called "get include folders from Visual Studio"  This option
would cause Coati to query the Visual Studio settings for include folders
(the VC++ project additional includes, the MSBuild user props files, any
per-computer MSBuild props files, and any custom props files specified
within the VC++ project).  Coati could display the global and per project
include paths that it got from Visual Studio, but keep these fields gray
(read only) when the checkbox is checked.

With this new "get include folders from Visual Studio" checkbox, Coati
would re-check the include paths every time the project is indexed.  So if
you change any of these settings in Visual Studio, then Coati would get the
new include paths before the next re-index.  After the reindex is done,
Coati could store copies of these include paths somewhere within the Coati
project file, for reference only.  Whenever the Coati project is opened it
could get the include folders from Visual Studio again, then check these
folders against the previously fetched folders.  If these paths have
changed at all, Coati could prompt the user that they need to reindex due
to changed include folders.

Include paths were simple with Visual Studio 2008 and older, but now it is
very complex.  Coati could deal with this complexity so the user does not
have to.

Regards,
- Michael

**Comment by mlangkabel** [comment]
Hi @Mike4Online. Thank you for all that information. For the new plugin we are simply planning to rely on Visual Studio to gather all the relevant include paths and resolve the macros used there. The plugin will let you select a configuration and a platform. Using this info it will generate a compilation database for all the projects you select. This compilation database can be read by Coati.

For the future we can expand the plugin to keep the exported compilation database up to date so Coati knows when to re-index the project.

**Comment by wrongway88** [comment]
We have added a feature to create a compilation database from the current VS solution which should resolve the issues with missing includes.

We now use the VS SDK to gather information about the solution and containing projects. Therefore the CDB creation happens from within VS (see the Coati documentation for details).  As of now this feature is considered beta, so it is introduced in parallel with the old project creation feature.
This also means that CDB are not yet automatically loaded into Coati, that has to be done manually (refer to the Coati documentation for details). This process will be automated in the future.

So even though the new feature is still a bit less convenient than the old one it should resolve the issues arising from all the different sources for include paths.
