### ISSUE TITLE
Project header file is not found (Unreal Engine 4 project)

### ISSUE THREAD

**Issue by pwinter1991** [CoatiSoftware/CoatiBugTracker#17]
All other header files are found except for the "project" header file which is basically included in every source file in an unreal project even though it lies in the same directory as the rest of the files which were found successfully.
![coati_ue4](https://cloud.githubusercontent.com/assets/5417215/11728176/9bb5a4c8-9f88-11e5-8f29-384326e5a2b8.png)

**Comment by egraether** [comment]
It looks like the source and header files are in different directories. My suspicion is that either the Include Path you entered is wrong, or you entered the Include Path after analyzing the project and then it didn't recognize the change when you added the Include Path.

Can you please check if the Include Path is right and then try a "Force Refresh" of the Project (Menu -> Edit -> Force Refresh).

**Comment by mlangkabel** [comment]
I think in that case Coati wouldn't have found the other headers as well. But regarding the screenshot it doesn't report any errors there. Your project settings look fine. 
The only difference I can see between the headers Coati has found and the header it hasn't found is that the questionable header's name contains an underscore. 
I'll investigate.

**Comment by mlangkabel** [comment]
I'm sorry to say that I could not reproduce your bug. Even after setting up the same directory structure Coati was still able to locate the header. 
So please try to force-refresh your project. If that doesn't work, you could try to add the include path to your source paths instead and force-refresh again.

**Comment by pwinter1991** [comment]
I will try asap a force refresh and hope for the best not so sure if I did it really in the correct order. Anyways a really interesting result.

**Comment by pwinter1991** [comment]
Sorry didn't have the time till now tried force refresh and creating a new coati project with the 0.4 version and still happens which is pretty strange.

**Comment by egraether** [comment]
The log file contains a lot of errors that read like this:
> ERROR: 'Engine.h' file not found

I assume that 'Engine.h' is a header file of Unreal Engine 4. You also need to add the path to those header files to the "Header Search Paths" in your project. Please let us know if you can successfully analyze then.

**Comment by fire** [comment]
Does this mean Coati does not support Unreal Engine 4?

**Comment by mlangkabel** [comment]
Unfortunately we didn't hear from pwinter1991 since the end of December.
In the meantime we have changed a lot in Coati's source code analysis. So we would be happy if someone would give it another try and use Coati on an Unreal Engine 4 Project ;)
If you have any issues while using Coati on Unreal Engine 4 Projects, please report them on this bug tracker. We would be very happy to investigate and fix them!

**Comment by fire** [comment]
There's a bit of a chicken and egg problem. I don't know if it'll work and testing on the project can only be done if Coati is licensed..

**Comment by mlangkabel** [comment]
I see! We'll investigate that for you and throw Coati on some open source UE 4 projects.

**Comment by fire** [comment]
If you need a sample project, [this one](https://github.com/tomlooman/EpicSurvivalGameSeries) is suitably complicated.

**Comment by pwinter1991** [comment]
Works fine for me now the "load project from solution" helps especially. Really great addition.

**Comment by mlangkabel** [comment]
@pwinter1991 nice to hear from you again! How does your project look inside Coati? Does it show all the nodes and connections you would expect to be there?
