### ISSUE TITLE
Can't change Font Face to any system font in the preferences on Linux

### ISSUE THREAD

**Issue by IgorDzreyev** [CoatiSoftware/CoatiBugTracker#172]
Guys, I really want to use Consolas and other fonts!!!

**Comment by egraether** [comment]
@IgorDzreyev There is a **font face** setting in the [Preferences Dialog](https://www.coati.io/documentation/#PreferencesWindow)
Does it not work if you change it to Consolas?

We just did some testing and found that there are problems on Linux. What platform do you use?

**Comment by IgorDzreyev** [comment]
Oh, my bad! I completely missed it. Thanks.

**Comment by egraether** [comment]
Fixed with 0.8.8
