### ISSUE TITLE
Project configured as C11 but Coati thinks it's C++11

### ISSUE THREAD

**Issue by dplong** [CoatiSoftware/CoatiBugTracker#177]
A pattern is forming. I double checked, and found that this project is indeed configured for C11, not C++11. However, I get "Error: invalid suffix on literal; C++11 requires a space between literal and identifier" for this line in a #define:

printf("%lu.%09lu: "format,(unsigned long) ... \

Coati highlights the "f" in "format." The ellipsis represents elided text.

**Comment by mlangkabel** [comment]
Hi @dplong, thanks for reporting! So is the other issue (#176) still valid?

**Comment by egraether** [comment]
Fixed with 0.8.16
Since this is a major bug in the current build with no possible workaround, we are releasing the maintenance release 0.8.21 today. Please download the new build and confirm if this is fixed. Thank you for reporting!
