### ISSUE TITLE
Debian Wheezy - Startup not possible

### ISSUE THREAD

**Issue by TGruenberg** [CoatiSoftware/CoatiBugTracker#18]
Dear Coati team,

I'm using Debian Oldstable Wheezy. There is no startup possible, in cause of some dependencies. I use an actual Linux kernel version, see "uname -an" output below.

Here the startup output:

-----------------------------------------------------------------

coati$ ./Coati.sh 
/home/tim/Coati/Coati-0.3.0-Linux/coati
/home/tim/Coati/Coati-0.3.0-Linux/coati/Coati: relocation error: /home/tim/Coati/Coati-0.3.0-Linux/coati/lib/libc.so.6: symbol _dl_find_dso_for_object, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

coati$ ./Coati
./Coati: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory

coati$ cat /etc/debian_version 
7.9

coati$ uname -an
Linux p1hee002 4.0.4 #1 SMP Tue Jun 2 13:51:48 CEST 2015 x86_64 GNU/Linux

-----------------------------------------------------------------

I think I need some newer libraries to startup Coati successfully.

Best regards,
Tim

**Comment by egraether** [comment]
Our build for Linux 64bit is currently done on Arch Linux. It's not fully downward compatible to older kernels, I suspect that's the problem here. We are currently working on building our Linux 64bit version on an older system. I will let you know.

**Comment by egraether** [comment]
Please test the Linux 64bit version of the new Coati Release v0.4 and let us know if your problem persists.

**Comment by egraether** [comment]
Closing due to one month without reply.
