### ISSUE TITLE
New install doesn't remember old project files

### ISSUE THREAD

**Issue by HarryDC** [CoatiSoftware/CoatiBugTracker#182]
When installing the new version of coati projects that where loaded into the old version are not in the UI anymore, not a big issue but quite inconvenient

**Comment by egraether** [comment]
Which platform do you use?

**Comment by HarryDC** [comment]
This is on Windows 7, I had the 0.7.22 version installed

**Comment by egraether** [comment]
Thank you! Our Windows installer is currently overwriting the whole installation, including Coati's preferences file. This will be fixed with the new Windows Installer in our next release.

**Comment by egraether** [comment]
Fixed with the new Windows installer in 0.9
When upgrading from 0.9 or a later version to any newer version it works as expected.
