### ISSUE TITLE
Errors in parsing a c file

### ISSUE THREAD

**Issue by HarryDC** [CoatiSoftware/CoatiBugTracker#183]
We have a C file in our set of files and from what I can tell that doesn't get parsed correctly, the error hint to some of the structs (but not all of them) that are in the .h file not being recognized. 

This is under 0.8.0

**Comment by mlangkabel** [comment]
Can you tell us what the error message reads, please?

**Comment by HarryDC** [comment]
some say `Error: unknown type name "xxx"` and some specify this even more via `Error: unknown type name "xxx" did you mean "Namespace::xxx"` in looking back at the include file it puts the declaration in a namespace guarded with `#ifdef __cplusplus` both VS and gcc don't have any issues with that.

**Comment by mlangkabel** [comment]
Coati is based on the Clang compiler but I don't think that this is an issue here.

If you used the manual project setup you may have selected C++ as language which is used for all of your source files. Right now this cannot be set per file using this project setup method. 

In case you created the Coati project using a compilation database the issue must be somewhere else because the compile command for each source file includes a flag that defines the language standard that is used. 

Which method did you use for your project?

**Comment by HarryDC** [comment]
The project was created with the previous version, coati did a rebuild, and there are actually a lot fewer errors than last time. I am guessing I used the VS solution, even though we create the project from CMAKE i am pretty sure I did not go with the compilation database. I can recreate the project using 0.8 and see what happens.

**Comment by mlangkabel** [comment]
Right now Coati's import for VS projects creates a project similar to the manually created project. So it just assumes one language for the entire project. This will change in the future. We are currently working on a new plugin that can export a compilation database for a VS solution. 

If the errors are non-fatal they should only have a very local effect on the index Coati creates. In case you want to get rid of them, you can either use CMake to export the compile commands for the project (described in [this chapter](https://www.coati.io/documentation/#ProjectSetupWizard) of our documentation) or wait for the new plugin ;)

**Comment by egraether** [comment]
The new Visual Studio plugin is now available within the download of our new release: https://www.coati.io/blog/release_0_9/

It will allow you to export a compilation database from your VS project, which acknowledges language and standard per file. You can use the compilation database then for project setup.

**Comment by egraether** [comment]
Moved core problem to a new issue: #230
