### ISSUE TITLE
Crash on changing font size

### ISSUE THREAD

**Issue by mipiro** [CoatiSoftware/CoatiBugTracker#186]
I'm encountering consistent segfaults when changing the font size:
- Open the tutorial
- Press Ctrl+0 to reset the font size
- Click on main()
- Click on my_first_step()
- Click on my_next_step()
- Click on the_central_hub()
- In graph_tutorial_4.h, click on ClassWithHiddenMembers::this_last_member
- Hold Ctrl+-
- Hold Ctrl++ if it hasn't crashed yet

It does not happen if I navigate to this_last_member directly via the search bar.

Console output:

```
QPropertyAnimation::updateState (opacity): Changing state of an animation without target
QPropertyAnimation::updateState (opacity): Changing state of an animation without target
QPropertyAnimation::updateState (opacity): Changing state of an animation without target
QPropertyAnimation::updateState (opacity): Changing state of an animation without target
Segmentation fault
```

Platform is Debian Jessie, kernel 4.6.0-1-amd64. Coati version is 0.8.0.

Log:
[log_2016-09-07_18-32-44_0.txt](https://github.com/CoatiSoftware/CoatiBugTracker/files/459734/log_2016-09-07_18-32-44_0.txt)

**Comment by mlangkabel** [comment]
I was able to reproduce this bug on Windows. It looks like the crash only occurs when changing the fontsize too quickly (before the re-draw is done).

**Comment by mlangkabel** [comment]
We just re-evaluated this issue using the new release Coati 0.10.0 and we haven't been able to reproduce this anymore on both, Linux and Windows :)
If anyone still has this kind of issue, please feel free to add another comment or open a new issue.
