### ISSUE TITLE
QT lib is trying to load fonts from (non-existing) Vagrant environment

### ISSUE THREAD

**Issue by mipiro** [CoatiSoftware/CoatiBugTracker#187]
At startup, this message is written to console 15 times:
`QFontDatabase: Cannot find font directory /home/vagrant/dev/Coati_External/Linux-x86_64/centos/Release/qt/lib/fonts - is Qt installed correctly?`

Fonts look fine though.

Platform is Debian Jessie, kernel 4.6.0-1-amd64. Coati version is 0.8.0.

Log:
[log_2016-09-07_18-50-28_0.txt](https://github.com/CoatiSoftware/CoatiBugTracker/files/459775/log_2016-09-07_18-50-28_0.txt)

**Comment by rojaster** [comment]
I got the same output into console

**Comment by st4ll1** [comment]
Fixed in 0.9.23 for 64 bit
