### ISSUE TITLE
Add a way to select multiple include directories at once when setting up a project from compilation database

### ISSUE THREAD

**Issue by titovroman** [CoatiSoftware/CoatiBugTracker#190]
This is frustrating a bit:
![coati-include-dir-multiple-selection](https://cloud.githubusercontent.com/assets/2725918/18422529/ce61b98a-78df-11e6-81c6-3fda62d646da.png)

AFAIK some (all?) Windows apps do it like this:

- ctrl-/shift-select multiple lines
- check/uncheck a checkbox on any selected line
- checkboxes of all selected lines get the same state as the clicked one

This is kinda counter-intuitive, but this will get the job done.

**Comment by egraether** [comment]
Fixed with 0.8.20
Allow line selection with SHIFT and added buttons for select/unselect all/selected.
