### ISSUE TITLE
Display basic datatypes differently

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#2]
Datatypes such as 'int' or 'char' are currently shown as undefined nodes in the graph, because they don't have a declaration in any source file.

Should they be displayed as defined nodes? Or have a different node style for basic datatypes?

**Comment by mlangkabel** [comment]
At least they should show a proper tooltip when hovering.

**Comment by payload** [comment]
+1

**Comment by mlangkabel** [comment]
implemented in Coati version 0.10.31
