### ISSUE TITLE
Shortcut after installation always runs some .msi files

### ISSUE THREAD

**Issue by pwinter1991** [CoatiSoftware/CoatiBugTracker#20]
(Only tested for Win10) The shortcut that is placed in the start menu calls always some .msi file that is placed in C:\Windows\Installer which starts after some further clicks the program (a dialogue shows up which says something with "please wait while windows configures coati") instead of calling the coati.exe directly.

**Comment by mlangkabel** [comment]
Can confirm the same behavior for Windows 7, even though I do not have to click anything when the installer is running,

**Comment by wrongway88** [comment]
I was able to find the cause of this issue. Should be gone in the next update.
