### ISSUE TITLE
crash when indexing single file

### ISSUE THREAD

**Issue by TypedLambda** [CoatiSoftware/CoatiBugTracker#218]
Selecting single files for indexing leads to an exception:

terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: Not a directory

**Comment by mlangkabel** [comment]
Hi @TypedLambda! Thanks for reporting. Did you enable the "Lazy Include Search" checkbox?

**Comment by TypedLambda** [comment]
Yes, that was checked.

**Comment by mlangkabel** [comment]
Glad to hear that. So it's the same issue as in #201. I'll close this issue :)
