### ISSUE TITLE
When edit Path open Folder Picker at current Path

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/CoatiBugTracker#22]
When opening the Folder Picker when editing a path (e.g. when editing a project), open it at the current path.

**Comment by egraether** [comment]
This is a duplicate of #11 
Qt uses the path of the executable when using a filepicker for the first time, but uses the last used path later on.

**Comment by wrongway88** [comment]
Not a duplicate.
in this case it shouldn't show the last opened path, it should show the path that's already in the box that's beeing edited

**Comment by egraether** [comment]
Yes, that's a good idea!
Fixed with 0.4.3.3
