### ISSUE TITLE
Crash on indexing Boost 1.60

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#225]
reported on Ubuntu 14.04 LTS

**Comment by st4ll1** [comment]
Boost 1.60 indexed on Archlinux(x86_64 Linux 4.8.2-1-ARCH) no fatal errors,
setup with compilation database (via bear).
I just got error because of wrong architecture:
5 errors(not fatal) like "not mips1", "not arm", ...
