### ISSUE TITLE
Not saving images unless you explicitly write the extension

### ISSUE THREAD

**Issue by ezetl** [CoatiSoftware/CoatiBugTracker#228]
Hello, I've just tried Coati.
I noticed that when I want to save a graph to an image, if I don't write the extension explicitly (e.g. "output.png") the image is not saved. No warning or error message. It's like if the image was saved successfully but it wasn't.
Coati offers 3 different extensions (png, bmp, jpg) in the dropdown menu when saving a graph, so why does it still require to explicitly write it? could this be a bug?

Regards,
Ezequiel

P.S: setup is: Linux rod 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:48:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux, ubuntu 16.04 LTS

**Comment by st4ll1** [comment]
Thanks for reporting.
Fixed in version 0.9.7
