### ISSUE TITLE
Cannot open coati 0.9 on windows after installation

### ISSUE THREAD

**Issue by knuthelv** [CoatiSoftware/CoatiBugTracker#231]
![image](https://cloud.githubusercontent.com/assets/22364474/19560126/799c3828-96d3-11e6-953d-428d4f20d520.png)

See image for error message.

**Comment by wrongway88** [comment]
Might be related to another issue caused by missing .dlls from the VC++ runtime redistribution. We are working on a fix for that which should be ready within the weak or so. I'll let you know asap.

**Comment by egraether** [comment]
@knuthelv Can you please try again with our new Release 0.9.23 and let us know if it works now?

**Comment by mlangkabel** [comment]
I'm closing this one now due to lack of confirmation that this is still a problem. If it still is, feel free to leave another comment or open a new issue.
