### ISSUE TITLE
_AFXDLL not being detected

### ISSUE THREAD

**Issue by mknafl** [CoatiSoftware/CoatiBugTracker#239]
My coati project has the following code in stdafx.h
```
#if !defined(_AFXDLL) && defined(_GXDLL)
# pragma message("If _AFXDLL is not specified the grid cannot be linked to as an Extension DLL\n")
# pragma message("To remedy this either change to link to MFC dynamically or remove _GXDLL from the project setting\n")
# error invalid configuration
# endif
```
This is flagged as an error, but is not an error in VisualStudio.  I can see the include for _GXDLL under the preprocessor directives.  After some searching it was suggested to be sure "Include MFC as shared DLL" was selected and to delete precompiled headers and rebuild.  This error is detected 3 times in my coati output.  How can I clear this error, or what do I have misconfigured?

**Comment by mlangkabel** [comment]
Hi @mknafl. That looks like an interesting issue :) Can you please tell us what the Coati error reads? Does it just say "invalid configuration"?
I don't know the project you are working on but maybe you can just define `_AFXDLL` in your Coati project settings. To do so just add "-d _AFXDLL" (without the quotes) to your list of Compiler Flags.

**Comment by mknafl** [comment]
That fixed my error, but I think it shows there must be some parsing for
symbols problem with Coati.  I believe _AFXDLL is a windows define.  Just
something to think about...

**Comment by mlangkabel** [comment]
@mknafl 
* why do you think that there must be parsing problems?
* I assume you are trying to analyze a visual studio project. Am I right?
* If so, did you use the Visual Studio plug-in to generate a Compilation Database for your Coatiproject?

**Comment by mknafl** [comment]
Malte,
Thanks for the suggestion to create a project from the compilation
database!  That fixed the errors!  Thanks!
Mark

**Comment by mlangkabel** [comment]
Awesome! Thanks for telling us :)
