### ISSUE TITLE
Need to re-enter license key when installing a new Coati version

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#244]
reported on Linux ubuntu xenial based flavor
also know issue on Windows

reported by mail

**Comment by egraether** [comment]
works for Windows now

**Comment by wrongway88** [comment]
Concerning Windows:
With Coati 0.9 we introduced a new installer. So when upgrading from 0.9 to newer version this issue should be resolved.
When installing 0.9 or newer when a version older than 0.9 is installed, it will be necessary to re-enter the licence.
