### ISSUE TITLE
Warn users when no Indexed Header Paths were set

### ISSUE THREAD

**Issue by mknafl** [CoatiSoftware/CoatiBugTracker#254]
![coati](https://cloud.githubusercontent.com/assets/11066044/21242826/c31002c6-c2db-11e6-8d2e-5b772620d3e8.jpg)
I have a project that has 310 files(which the overview says), but it says I only have 9 classes.  This is clearly not the case.  I am guessing there is something about how my classes are terminated or something?  Any ideas why I might be seeing this strange behavior?  BTW, your software did help me fix literally 1000+ "errors" that were not detected by visual studio.  I am trying to see if this strange behavior indicates some other strangeness.  Thanks!

**Comment by egraether** [comment]
My guess it that you didn't set any **Indexed Header Paths** during project setup, so you only indexed your source files, without the corresponding header files.

To confirm that please click on the **Files** node in the overview. I think it will only show ```.cpp``` files and no ```.h``` files, right?

To fix this, add your project root directory to **Indexed Header Paths** so Coati knows that any included file within that directory should be indexed as well. Please let me know if this fixes the issue.

Did you use our Visual Studio plugin for creating the compilation database? The **Indexed Header Paths** will be automatically set in the newest version released yesterday with our [new build](https://www.coati.io/downloads). You might want to give it a try.

**Comment by mknafl** [comment]
That did fix that!  One other issue, I have used #import for excel.  I
needed to #include "excel.tlh" to silence an error.  It causes an
additional 18476 errors!  I have excluded the directory, but is there a way
to exclude a file?

**Comment by egraether** [comment]
Yes, you can exclude files and directories from indexing by adding them to **Exclude Paths** in the **Advanced Settings** of the **Edit Project** dialog. These files will still be accessed during indexing, but the information won't get stored. If they cause fatal errors, you will still see them though.

**Comment by mknafl** [comment]
That worked!  Thanks!

On Fri, Dec 16, 2016 at 12:59 AM, Eberhard Gräther <notifications@github.com

**Comment by egraether** [comment]
Solved with 0.10.82
Warning users now if no Indexed Header Paths were set.
