### ISSUE TITLE
Avoid project re-parsing when opening project via file association (windows)

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/CoatiBugTracker#26]
Projects get re-parsed when opened directly (double klicked) rather than via open-project dialog in coati

**Comment by wrongway88** [comment]
Tried again, might yet have something to do with conflicting version numbers (db against exe)

**Comment by egraether** [comment]
Maybe your installed exe has a different version than your development build?

**Comment by egraether** [comment]
Was not spotted in 2 months. Closing.
