### ISSUE TITLE
Graph shows the same class multiple times in some cases

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/CoatiBugTracker#260]
Reported via Mail.

Original text:
"its kind of confusing that in the graph, classes show up several times
e.g. I am investigating the usage/references to Class C. Class A and B use it in their members but they show up twice, once as a big node with the variables showing and then once with this paper icon, where just the file name is shown…. Maybe there is some good reason behind it but I didnt understand it and it makes the graph more crowded"

**Comment by mlangkabel** [comment]
This seems to be a misunderstanding: The two nodes do not stand for the same thing.

The "big node" is indeed the class node but the other one "with the paper icon, where the file name is shown" is the file node. So Coati does not only display classes, methods and fields but also files. 

In your use case the class A seems to have a member variable of type C but the file `A.java` has an import edge to the class C. So Coati does not only enable you to see where a class is instantiated but also shows you where something is imported (This may also come in handy for static methods ;) ).

**Comment by mlangkabel** [comment]
With the release of Coati 0.10 these file nodes will be bundled as "importing files" so you don't have a separate file node for each importing file crowding your graph ;)
