### ISSUE TITLE
Global header search paths not saved to AppSettings

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#27]
antergos linux, with gcc 5.3.0

**Comment by jaked122** [comment]
Huh, so this is where [it](https://www.reddit.com/r/cpp/comments/47de5c/coati_the_source_explorer/d0ch3jg) went. Thanks for filing this one.

It's also present on Windows.

**Comment by egraether** [comment]
Fixed with 0.5.0.4
There was a missing save call to the app settings.
We will do a new maintenance release soon.
