### ISSUE TITLE
Can't handle multiple files with same name

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#271]
Reported by mail

**Comment by mlangkabel** [comment]
It looks like this is only an issue when activating the file node using the search bar. Clicking the file node in the graph or the file name in the code view activates the correct file in the correct location.

**Comment by egberts** [comment]
It should associate indexing of any filename by its own internal hash value.   For a real example, Bro IDS makes use of the same filename `events.bif.h` in each protocol-specific directory.

I often wonder which of the `events.bif.h` include file it is going to pull from (hopefully it checks the local directory where the source file is located at...firstly.

**Comment by mlangkabel** [comment]
Fixed with Coati version 0.10.19
