### ISSUE TITLE
Coati.dmb image not recognized

### ISSUE THREAD

**Issue by sixcorners** [CoatiSoftware/CoatiBugTracker#273]
<img width="372" alt="screen shot 2017-01-10 at 2 34 30 pm" src="https://cloud.githubusercontent.com/assets/585501/21823748/140ce4bc-d742-11e6-9a3c-177646d16c52.png">
Downloaded from here: https://www.coati.io/downloads/latest/osx/64bit
but that redirected to an http download.

**Comment by wrongway88** [comment]
We are having some issues with our website and download server right now, we will notify you when it's up again asap.

**Comment by wrongway88** [comment]
The download server is back up. Please let us know if you still have troubles.

**Comment by egraether** [comment]
Was probably related to the server issues. Closing now.

**Comment by sixcorners** [comment]
The issue seems to be that something on my company's network is doing something weird to the file. When I download it elsewhere it is fine. If the download happened over https this wouldn't happen but I guess it's not really an issue. Thanks anyway.
