### ISSUE TITLE
Can't see usages of template member when activated

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#282]
definition:
```
template <typename Message>
auto Publish(TypedTopic<Message> t) -> ErrorOr<NodePublisher<Message>> {  
....
}
```

Usage:
```
// macro TRY
#define TRY(...)                                                   \
    ({                                                             \
        auto res = __VA_ARGS__;                                    \
        if (!res.isOk()) {                                         \
            typedef details::ResultErrType<decltype(res)>::type E; \
            return types::Err<E>(res.storage().get<E>());          \
        }                                                          \
        typedef details::ResultOkType<decltype(res)>::type T;      \
        res.storage().get<T>();                                    \
})

auto ints = TRY(node->Publish(topics::Ints()));
```

**Comment by mlangkabel** [comment]
If you click the definition of `Publish<Message>(....)` Coati only shows the definition of the template method in the code view and displays the according node in the graph. 

Additionally Coati adds a node for each specialization (explicit or implicit) of this method to the graph. This way you can easily see which types are used as template arguments to instantiate this method throughout your code base. So if you would click the node for `Publish<int>(....)` the code view shows all the places where the generated method using `int` as a template argument is used.

If you click `Publish` in `auto ints = TRY(node->Publish(topics::Ints()));` you activate the (probably implicit) specialization of the `Publish(TypedTopic<Message> t)` method. The graph will show the specialization node being the source of a `template specialization` edge leading to the actual definition of this method.
