### ISSUE TITLE
segfault in tictactoe selecting node with Enter key

### ISSUE THREAD

**Issue by payload** [CoatiSoftware/CoatiBugTracker#285]
Coati version 0.10.0
The steps to reproduce the segfault:
* open tictactoe
* Ctrl+F main
* leave Enter key pressed
* segfault

**Comment by mlangkabel** [comment]
Reproducible on Windows 7. Thanks for reporting this issue @payload!

**Comment by mlangkabel** [comment]
Fixed with Coati version 0.10.9
