### ISSUE TITLE
Indexing a project by intercepting clang invocation?

### ISSUE THREAD

**Issue by TTimo** [CoatiSoftware/CoatiBugTracker#288]
Have you considered indexing a project by intercepting clang invocation? Specifically to extract include paths and defines set by the build system?

The lazy include search is completely impractical (too slow, consumes all resources until OOM'ed), and manually giving all the header include paths needed takes a significant setup and maintenance effort (360 entries in my "header_search_path" section atm, and still some files won't parse completely).

It seems a wrapper to build all that information from a build of the project could be a nice solution there.

**Comment by egraether** [comment]
That's an interesting idea that we haven't tried so far. It might be possible to create a clang Compilation Database which we already support for project setup: https://www.coati.io/documentation/#VisualStudio

**Comment by TTimo** [comment]
Looks like Bear already does this according to your documentation. I will see if I can use it or generate my own compatible database.

**Comment by TTimo** [comment]
Bear intercepts clang and the coati project built from that works just fine.

From a UX perspective it would be nice if Bear was integrated in Coati directly, so you could create a project by typing in the build command directly (create project database by instrumenting a build).

Closing this though, I don't particularly need the UX niceties myself.
