### ISSUE TITLE
The flexible windows UX is terrible, add "Reset Windows" option

### ISSUE THREAD

**Issue by TonnyTao** [CoatiSoftware/CoatiBugTracker#289]
Mac
Coati 0.10.0

Flexible windows layout really depressed me. I spend a half hour to reset windows as:

http://www.coati.io/assets/frontend/concept-423b90c1648a05b6bafa946c343a67d4afe141d728d0bc821c09c84e417e18eb.png

How about adding a "Reset Windows" menu item?

**Comment by egraether** [comment]
We are using the standard implementation of QDockWidget at the moment, but I agree that's it's not super intuitive.

**Comment by mlangkabel** [comment]
implemented with Coati 0.11.77
