### ISSUE TITLE
Crash on Windows for UrHo3D project

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#30]
Windows log: https://gist.github.com/ViteFalcon/246edcb3c730224354d9

**Comment by ViteFalcon** [comment]
Thanks, @egraether for looking at this. I'm attaching the log files with this.
[log.zip](https://github.com/CoatiSoftware/CoatiBugTracker/files/146291/log.zip)

**Comment by egraether** [comment]
@ViteFalcon Thank you for the log files, it looks like the analysis crashes after:
```
01:39:13 | INFO: type usage: unsigned int Urho3D::BatchQueue::GetNumInstances() const -> unsigned int <C:/Users/ullatil/Documents/Visual Studio 2015/Projects/RokLegend/dependencies/Urho3D/include/Urho3D/Graphics/Batch.cpp 863:5 863:12>
```
We will look into this.

##### Sidenote:
I guess you set up your Coati project by passing in a Visual Studio solution and this solution included the source files of the whole Urho3D engine. Is that right?

Do you want to analyze the internals of Urho3D, or are you just interested in your own project files?

Coati works best if you just analyze you project files, the files you are actually working on. For frameworks and engines you provide the header search paths. Unfortunately, Coati can't tell from your Visual Studio Solution which files are you project files, and which ones are Urho3D files. For this you would need to do a manual project setup.

**Comment by ViteFalcon** [comment]
I want to analyze Urho3D as I want to understand and learn it quicker. I also want to analyze my project. I tried manual project, which managed to crash as well.

**Comment by ViteFalcon** [comment]
The other issue I'm seeing is with Coati not saving Global Header Search Paths. I have created another issue to address that; #31.

**Comment by egraether** [comment]
@ViteFalcon I had a look at Urho3D. It was bit a of a hassle, because I had to make a build first, apparently some headers get generated. I managed to analyze the source files in Source/Urho3D, which worked fine, except for some errors. I didn't fix all external dependencies properly.

Then I looked at where your log files stopped. I found out that the logs always stop when the analysis is at the end of a file, so maybe it's the file after the last analyzed file that causes the crash.

Could you please provide us the Coati project file `*.coatiproject` you used?

**Comment by wrongway88** [comment]
I managed to reproduce the problem. I will deal with it asap.

**Comment by ViteFalcon** [comment]
Awesome! Sorry for not responding to the previous request. Would it be possible to give an idea about what exactly happened?

**Comment by wrongway88** [comment]
I've tried around a couple times resulting in one crash but I couldn't reproduce it since. There was an issue with project setup from VS solution which should be resolved by now (in the next released plugin version).
As for the Coati crash I can not say yet, considering that you tried manual project setup as well. So I'm afraid I cannot say what exactly happened (not yet anyways).
It would be interesting to know whether you've build Urho3D before parsing it with Coati or not? Like @egraether  said, some header files are created when building.

**Comment by egraether** [comment]
@ViteFalcon Since we cannot really reproduce the problem, I am closing this issue now. We will release a new build next week, running more stable and including a lot of fixes. Please reopen if your problem persists and we will look at it again.
