### ISSUE TITLE
package undefined

### ISSUE THREAD

**Issue by TonnyTao** [CoatiSoftware/CoatiBugTracker#306]
package undefined

Mac
Coati 0.10.0

![](https://i.imgsafe.org/d2e7f717e5.png)

**Comment by mlangkabel** [comment]
Oh, this is just a case of really bad wording. What "undefined" really means is that this node is used by your source code but has no definition in the indexed code base. We will rename that tag to "non-indexed" in the future.

**Comment by mlangkabel** [comment]
Hm, what strikes me here is that all the other io.reactivex packages are indexed and the `internal` package is not. Are your source files that define content of the `internal` package located in a folder that is not inside your project paths? Or did you exclude the `internal` folder from your project?

**Comment by mlangkabel** [comment]
Nevermind! I couldn't resist to setup the project myself. Good news: I was able to reproduce the issue and I think I can already guess what causes the package to render as undefined :)

**Comment by mlangkabel** [comment]
Fixed with Coati version 0.10.29
