### ISSUE TITLE
Global Header Search Paths are not getting saved

### ISSUE THREAD

**Issue by ViteFalcon** [CoatiSoftware/CoatiBugTracker#31]
**What?**: Global Header Search Paths does not get saved and disappears upon restarting Coati.

**How to reproduce?**
1. Open a project that has errors.
2. Go to 'Help' -> 'Preferences...'
3. Add header file locations.
4. Click 'Save'
5. Restart Coati

**What is expected?**: The paths added to Global Header Search Paths should stay

**What happens?**: There are no paths listed in Global Header Search Paths.

**Comment by ViteFalcon** [comment]
I just noticed the duplicate issue #27

**Comment by egraether** [comment]
@ViteFalcon I was in the process of writing you that :)

**Comment by egraether** [comment]
@ViteFalcon We are currently building a new release that includes this fix.
