### ISSUE TITLE
Can't find IntelliJ plugin in Android Studio

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#316]
No result is returned when searching coati in Android Studio > Preferences > Plugins > Install JetBrains plugin

**Comment by st4ll1** [comment]
The version 0.4.4 of the plugin idea-coati should be found.
Android Studio > Settings > Plugins > Browse repositories... 
and not 
Install JetBrains plugin, there are only plugins published from JetBrains 

tested with Android Studio 2.2.3
