### ISSUE TITLE
Java symbols from src.zip are not found or used

### ISSUE THREAD

**Issue by utrott** [CoatiSoftware/CoatiBugTracker#332]
On CENTOS 6.8, java is autodetected with: 
    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el6_8.x86_64/jre/lib/amd64/server/libjvm.so

The src.zip of the SDK is in:
        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el6_8.x86_64/src.zip

Nonetheless, Symbols such as:
        java.util.Set and 
        java.util.Set<>.size()
are not detected and remain undefined.

This is quite often the case for symbols defined in src.zip it seems.

**Comment by mlangkabel** [comment]
@utrott thanks for reporting this one. I think it's just a wording related issue. The tag "undefined" just means that Coati didn't find a definition for that symbol inside the indexed source files. We are thinkiong abour renaming this tag to "non-indexed".

**Comment by mlangkabel** [comment]
Implemented the rename with Coati version 0.10.60
