### ISSUE TITLE
Visual studio headers cause errors

### ISSUE THREAD

**Issue by jaked122** [CoatiSoftware/CoatiBugTracker#34]
Visual studio integration aside, some of the not quite standard features that Microsoft is known for seems to be causing errors in the their header files. 

I doubt that this is affecting the parsing of my project, however, it is a bit frustrating, and after trying out several of the Visual Studio include paths, it seems that Visual Studio 2013 has the fewest errors. The error that appears is from a file in any of the paths which I have added to the project.

![Error display](http://i.imgur.com/JdTphaa.png)

Most strangely of all, I can't figure out where it's found this file from. It's not in the directories I've pointed it at, neither the Visual Studio include files, nor the SFML installation on my system have any references to this file.

I've also gone into the logs and found no mention of where this file is, it reports that the error is present, but does not show the error itself.

**Comment by mlangkabel** [comment]
@jaked122: To find out where the file is located just hover the file name "combaseapi.h" and Coati will display the file's path.

First of all: These errors should't affect Coati's code analysis. 
I can understand that this is bothering you, so i did some research. If you are having errors that state something like `use of undeclared identifier 'char16_t'` they can be fixed. These types are builtin for the MSVC compiler and there is a compatibility mode for clang to cope with these types as well. It can be enabled via compiler flags. They can be set by manually editing the *.coatiproject file. Just open the file in a text editor and add the following tags as child nodes of your `<source>` node:
```
<compiler_flags>
	<compiler_flag>-fms-extensions</compiler_flag>
	<compiler_flag>-fms-compatibility</compiler_flag>
	<compiler_flag>-fms-compatibility-version=19.00</compiler_flag>
</compiler_flags>
```
Besides the errors mentioned above, it doesn't fix the IUnknown error you posted. There is a discussion to add this magic microsoft define to the clang ms compatibility mode. So this error is probably gone when we upgrade Coati to the upcoming clang release. I will close this issue for now but it can be reopened if this stays an issue in the future.

**Comment by mlangkabel** [comment]
As a result of your post I just filed 2 new feature requests:
#37 _Set compiler flags via GUI_: It seems like compiler flags are becoming important right now. Going into the XML for manual edits is not the best way to go ;)
#38 _Show fatal errors of code analysis_: These are the errors you should worry about. Coati needs to display if there are any of these.
