### ISSUE TITLE
Variables in global namespace are shown within std namespace

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#344]
reported on Windows 10 for Coati 0.10.0

**Comment by mlangkabel** [comment]
I have tried to reproduce this by declaring a global variable and accessing it using the global ("::") namespace descriptor. There is no "std" namespace showing up in Coati, so I couldn't reproduce this issue. If anyone comes across this issue and has an example code ready, please post it here.

**Comment by egraether** [comment]
Was most likely related to indexing errors.
