### ISSUE TITLE
[Feature] Add "Reset Views" to the View menu

### ISSUE THREAD

**Issue by king7532** [CoatiSoftware/CoatiBugTracker#347]
As a new user to Coati, I accidentally moved and closed some of the views (Search, Code, Status), and I would like an easy way reset all the views to back to their default positions and state when I installed the app.

For example, the [Affinity Designer](https://affinity.serif.com/en-us/designer/) app has a View menu command called "Studio -> Reset Studio" which restores all the in-app views back to their original position and state.

**Comment by mlangkabel** [comment]
Hi @king7532, thanks for reporting this one. We have seen this request before (#289) and to be honest: our dev team has the same issue ;)

I'll close this feature request now so we only have one issue open for this.

**Comment by king7532** [comment]
Duplicate of #289.
