### ISSUE TITLE
Set compiler flags via GUI

### ISSUE THREAD

**Issue by mlangkabel** [CoatiSoftware/CoatiBugTracker#37]
Even though Coati already supports compiler flags this feature is quite hard to find. To specify such a flag the user needs to open the *.coatiproject file in a text editor and add them manually as child nodes of the `<source>` node in the following way.
```
<source>
    <compiler_flags>
        <compiler_flag>...</compiler_flag>
    </compiler_flags>
<source>
```
For the future it should be possible to view and enter these flags in the project setup wizard and in the project settings.

**Comment by egraether** [comment]
Added compiler flags UI to project setup summary with 0.5.0.14
