### ISSUE TITLE
Add home-button to return to overview

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#40]
Currently this can by done by using the keyword 'overview' in the search bar.
A button would be more straight forward, but also clutters the UI.
Opinions?

Vote with +1 or -1

**Comment by egraether** [comment]
+1 via mail (27.2.2016)

**Comment by mlangkabel** [comment]
+1 (I think we should give this a try)

**Comment by wrongway88** [comment]
+1

**Comment by patrikfors** [comment]
+1

**Comment by ChriZzZ** [comment]
+1 AND add a keyboard shortcut like CTRL+HOME
you could make the buttons to be displayed configurable to avoid overloading the UI of users that like it clean

**Comment by egraether** [comment]
Added button left of search bar and shortcut CTRL+HOME with: 0.5.3.5
