### ISSUE TITLE
Crash if you try to open project without having sufficient access rights

### ISSUE THREAD

**Issue by cwinkler89** [CoatiSoftware/CoatiBugTracker#43]
When I try to open a Coati Project from a protected directory (in my case C:\Program Files (x86)\SomeFolder) Coati crashes. 

NOTE: All source files referenced in the project are also inside a subfolder of Program Files.

**Comment by wrongway88** [comment]
Crash appears when Coati tries to modify the project database.
Added error handling for next release.
