### ISSUE TITLE
Using CTRL+MouseWheel (unlocked) causes Coati to become unresponsive

### ISSUE THREAD

**Issue by ChriZzZ** [CoatiSoftware/CoatiBugTracker#44]
I am assuming that CTRL+Wheel changes the font size by one step?!

Using an unlocked mouse wheel I can cause Coati to soft lock into a "refresh loop" because of the thousand "change font size instructions". Even worse: If I try to type into the search bar while Coati is in that state will cause the auto complete result list to be drawn over other applications once Coati reaches the point when it processes these UI inputs.

**Comment by wrongway88** [comment]
Refreshing the UI is now avoided after hitting zoom limits
Bug will be gone in next release

**Comment by egraether** [comment]
Also added a delay between mouse wheel events with 0.5.0.23
