### ISSUE TITLE
New project/setup type dialog too small on Windows10

### ISSUE THREAD

**Issue by patrikfors** [CoatiSoftware/CoatiBugTracker#46]
The dialog for creating a new project and selecting type of setup (simple or too small) is too small. Not all elements are visible. It is possible to scroll down to the advanced radio button but not to show all text.

See attached screen shot
![coati_new_project_dialog](https://cloud.githubusercontent.com/assets/693788/13463707/e35c00e2-e08d-11e5-93ac-30259323d60b.png)

**Comment by egraether** [comment]
@patrikfors Thanks for reporting!
We will look into this. Font sizes in the GUI vary on each platform for some reason. This case looks extreme though.

Here is a workaround for now:
Open the file `C:\Program Files (x86)\Coati Software\Coati\data\gui\project_wizzard\window.css` and change the font-size setting on top:
```
* {
	font-size: 12pt;
}
```
to something smaller like:
```
* {
	font-size: 10pt;
}
```

Hope this helps!

**Comment by egraether** [comment]
Fixed with 0.5.1.7
Window size adapts to content size now.
