### ISSUE TITLE
Version upgrade of VS plugin not working

### ISSUE THREAD

**Issue by ChriZzZ** [CoatiSoftware/CoatiBugTracker#62]
I tried to upgrade from 0.5.0.4 to 0.5.1.21

Upgrading Coati itself worked fine, but installing the VS plugin displayed an error.
Based on the log it seemed that it refused to upgrade an existing version so I uninstalled the previous plugin via Visual Studio. However, I still get the same error.

Here is the log the VSIX Installer generated:

21.03.2016 10:33:34 - Microsoft VSIX Installer
21.03.2016 10:33:34 - -------------------------------------------
21.03.2016 10:33:34 - Initializing Install...
21.03.2016 10:33:34 - Extension Details...
21.03.2016 10:33:34 - 	Identifier         : acf15780-03b5-440e-a41e-db79b7043fc2
21.03.2016 10:33:34 - 	Name               : CoatiPlugin
21.03.2016 10:33:34 - 	Author             : Coati Software OG
21.03.2016 10:33:34 - 	Version            : 0.5.1
21.03.2016 10:33:34 - 	Description        : This package allows Coati to communicate with Visual Studio and vice versa.
More infos at www.coati.io
21.03.2016 10:33:34 - 	Locale             : en-US
21.03.2016 10:33:34 - 	MoreInfoURL        : 
21.03.2016 10:33:34 - 	InstalledByMSI     : False
21.03.2016 10:33:34 - 	SupportedFrameworkVersionRange : [4.5]
21.03.2016 10:33:34 - 
21.03.2016 10:33:34 - 	SignatureState     : Unsigned
21.03.2016 10:33:34 - 	Supported Products : 
21.03.2016 10:33:34 - 		Microsoft.VisualStudio.Pro
21.03.2016 10:33:34 - 			Version : [11.0]
21.03.2016 10:33:34 - 
21.03.2016 10:33:34 - 	References         : 
21.03.2016 10:33:34 - 		-------------------------------------------------------
21.03.2016 10:33:34 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
21.03.2016 10:33:34 - 		Name         : Visual Studio MPF 11.0
21.03.2016 10:33:34 - 		Version      : [11.0]
21.03.2016 10:33:34 - 		MoreInfoURL  : 
21.03.2016 10:33:34 - 		Nested       : No
21.03.2016 10:33:34 - 
21.03.2016 10:33:34 - Signature Details...
21.03.2016 10:33:34 - 	Extension is not signed.
21.03.2016 10:33:34 - 
21.03.2016 10:33:34 - Searching for applicable products...
21.03.2016 10:33:34 - Found installed product - Microsoft Visual Studio Community 2015
21.03.2016 10:33:34 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
21.03.2016 10:33:34 - Found installed product - Global Location
21.03.2016 10:33:34 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ChriZzZ** [comment]
PS: Reinstalling the 0.5.0.4 version of the plugin worked!

**Comment by wrongway88** [comment]
Thanks Chriz, the release contains a wrong version of the VS2015 plugin binaries

These should work now:
https://dl.dropboxusercontent.com/u/17330041/Coati/coati_plugin_vs_2015.vsix

**Comment by ChriZzZ** [comment]
Confirmed!

**Comment by mlangkabel** [comment]
Fixed with release of Coati 0.6.0.0
