### ISSUE TITLE
Cannot install application on account with limited access

### ISSUE THREAD

**Issue by MojaveWastelander** [CoatiSoftware/CoatiBugTracker#63]
I tried to install application on a system with limited access rights (domain user account) and I get following error: "Error 1001. An exception occurred during the Commit phase of the installation. This exception will be ignored and installation will continue. However, the application might not function correctly after installation is complete. --> Access to the path 'C:\ProgramData\Microsoft\Windows\Start Menu\Coati\' is denied", after which another error appears: "Error 1001. Could not find file 'd:\Progs\Coati\install\SetupRemoveCacheFiles.InstallState'.", then installation is interrupted.

**Comment by wrongway88** [comment]
I'm guessing you don't have access rights for 'C:\ProgramData\Microsoft\Windows\Start Menu\Coati\' ?
During installation Coati copies files to the

- install directory (usually 'C:\Program Files (x86)\' or whatever you chose)
- appData directory ('C:\Users\UserName\AppData\Local')
- start menu directory ('C:\ProgramData\Microsoft\Windows\Start Menu')

can you confirm that you can install to the appData directory and your chosen install directory? If those work I can provide a workaround

**Comment by MojaveWastelander** [comment]
There  are no files in AppData after installation (interrupted installation), in selected install directory there is just a folder **install** with some *.tmp files. In general this application should not need access to system directories, maybe adding a common installer option with "Install for all users"/"Install current user"?

**Comment by wrongway88** [comment]
Thanks for the quick answer @MojaveWastelander 
- Coati currently creates a start menu entry by default, which should be the source of the initial problem.  This will be removed/made optional.
- There is a larger update to installer planned for the near future, we I'll try to add an "Install for all users"/"Install current user" option by then.
- As for statically linking VC redist dependencies, this is a bigger issue. This will most likely cause issues with other dependencies, so it would take some time. We'll try to provide a solution as soon as we can.

Thanks again for your report and sorry for the inconvenience.

**Comment by mlangkabel** [comment]
With Coati 0.5.3.38 we removed the VC++ redistributable dependency and are shipping all the required dlls with the Coati installer. So for the future there is no need for you to install anything but Coati ;)

**Comment by mlangkabel** [comment]
@MojaveWastelander: For the new release of Coati 0.6 we made the shortcut in the start menu optional. This should solve your problem regarding access rights.
