### ISSUE TITLE
Feature Request: Project from makefile

### ISSUE THREAD

**Issue by cwinkler89** [CoatiSoftware/CoatiBugTracker#65]
Setting up the include paths and source file locations manually takes way to much time. I would like to see parsing of makefiles.

**Comment by st4ll1** [comment]
If you are on an Unix system you can try this workaround. Use [Bear](https://github.com/rizsotto/Bear) to generate a JSON Compilation Database. With the Database you can create a new Project. 
I just tested it on [Poco](http://pocoproject.org) without any problem.

**Comment by egraether** [comment]
We also added this to our documentation [here](https://www.coati.io/documentation/#CreateAProjectFromCompilationDatabase)
