### ISSUE TITLE
Text does not render properly with High DPI settings

### ISSUE THREAD

**Issue by speps** [CoatiSoftware/CoatiBugTracker#66]
Text in the interface appears cut in places when Windows is set to text size bigger than 100%.

![2016-04-03 18_59_56-coati - tutorial coatiproject](https://cloud.githubusercontent.com/assets/16678/14394907/8834af60-fdc6-11e5-9b13-6f8c7378d423.png)
![2016-04-03 19_00_04-coati - tutorial coatiproject](https://cloud.githubusercontent.com/assets/16678/14394908/89f24f6a-fdc6-11e5-9a42-f4fa1ace0449.png)

**Comment by egraether** [comment]
It's not just the text, the icons are also too big.

@speps What Windows version are you using?

**Comment by speps** [comment]
This is on Windows 10 Version 1511 (OS Build 10586.164).

**Comment by egraether** [comment]
Thank you! We can reproduce the problem.

**Comment by mlangkabel** [comment]
Fixed with Coati 0.5.3.42
