### ISSUE TITLE
Exclude sub-directories from project paths

### ISSUE THREAD

**Issue by anestisb** [CoatiSoftware/CoatiBugTracker#68]
It's a common pattern that project structure includes sub-directories with 3rd-party components and other deps that are not important when indexing & analyzing target project codebase.

It would really useful if a GUI configuration-based solution (e.g. via ADVANCED project settings) or a file annotation based solution (e.g. .coatignore file in root dir to be ignored) is introduced to cover such cases.

**Comment by mlangkabel** [comment]
Thanks a lot for the feedback @anestisb! Both of the approaches you describe sound good, even though I'd prefer the former one because it doesn't involve cluttering the file system ;) On the other hand side the latter approach seems more comfortable when those ignored folders are moved around. But how often is a folder that contains 3rd-party code moved in practice?
What do you think?

**Comment by anestisb** [comment]
Yup totally agree with your points. I also think it's very rare that 3rd-party code locations move around projects' directory structure throughout its lifetime. So having an option at the project settings level sounds more elegant at the moment.

At any case as a general note, being a user of many code indexing solutions, I wouldn't mind to deal with such customization at the file system level considering:
* Special files can be easily excluded/ignored from versioning, searching, diff-ing & editor tools
* Can be easily scripted (e.g. in conjunction with makefiles or post compilation scripts) to create more complex configurations faster (e.g. keep generated headers from internal subdirs but ignore src codebase)
* No additional overhead to configuration menus. Have seen this pattern quite often in similar tools: the initially clean & fast configuration structure explodes with nested & complex options.

**Comment by mlangkabel** [comment]
As a clean and fast configuration structure is one of our major goals we will reconsider our options here and let you know once we have implemented a solution.
Right now the only way to ignore certain paths is by not adding them to the coatiproject ;) This means you need to get into your folders and add the remaining paths. To set this up **as fast as possible** you can drag and drop the folders from your file system browser right into the path listbox of your project settings. So there's not much typing involved!

**Comment by egraether** [comment]
Implemented with 0.6.2.1:
Added logic and UI for excluding files and directories from analysis. UI is located in the "Advanced Settings" of the "Edit Project Window".
