### ISSUE TITLE
High DPI support on Linux is wonky

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#69]
check system scale for menus and title bars

**Comment by st4ll1** [comment]
The High DPI support on Linux depends primary on the used desktop environment. But there are other configurations like specific settings for Qt applications. 
The [HiDPI Wikipage](https://wiki.archlinux.org/index.php/HiDPI) from Archlinux Wiki covers a lot configurations for HiDPI. 

Tested on Archlinux with i3 on a 4k Monitor using the Qt and XServer configuration mentioned on this page. 
Tested on Ubuntu 15.04 as well.
