### ISSUE TITLE
re-analyzing a project gets stuck at "Loading Project:..."

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#84]
Following lines are logged in the terminal:

QWaitCondition: cv destroy failure: Device or resource busy
QWaitCondition: mutex destroy failure: Device or resource busy

**Comment by egraether** [comment]
Reportet on linux x64, manjaro 15.12

**Comment by mlangkabel** [comment]
We have been unable to reproduce this issue. It hasn't been reported again in the last 7 month, so we are closing this issue now.
