### ISSUE TITLE
Activating symbol via Plugin from Sublime Text 3 not working

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/CoatiBugTracker#85]
Reportet on linux x64, manjaro 15.12
Sublime Text 3 error log on startup:
LookupError: unknown encoding: idna

**Comment by st4ll1** [comment]
Not reproduced, fix according to http://stackoverflow.com/questions/9144724/unknown-encoding-idna-in-python-requests in Version 0.6.1-25
