### ISSUE TITLE
Performace and stability issues

### ISSUE THREAD

**Issue by MojaveWastelander** [CoatiSoftware/CoatiBugTracker#86]
So I tried yesterday to run newly 'open-sourced' [CRYENGINE ](https://github.com/CRYTEK-CRYENGINE/CRYENGINE)through Coati and the results are not that good. There are about 4000 files in CryEngine folder and Coati goes pretty well with first 500 files, after that it works slower and slower up to the point when it is mostly unresponsive and just load 2 cores on CPU. Can you take a look and see if you have such issue?

**Comment by mlangkabel** [comment]
@MojaveWastelander thanks for reporting this! In addition to implementing new features we are constantly working on improving the overall performance. As a result the next release will enable **multithreaded** code analysis. Even though it is not fully optimized yet it will bring down analysis times to **30 - 40%** of what's currently happening.
I think that performance will be much better with the next version but please contact us if you are still experiencing show stopping issues by then!
