### ISSUE TITLE
Problem with additional windows in GUI

### ISSUE THREAD

**Issue by dukebarman** [CoatiSoftware/CoatiBugTracker#93]
I don't see buttons in additional windows:

![manjaro-2016-06-10-19-54-01](https://cloud.githubusercontent.com/assets/1186777/15972111/42ab70e0-2f45-11e6-881f-1b6aaea9f3bd.png)

Maybe because you add static libraries? 

```
    $ coati 
    libpng warning: iCCP: known incorrect sRGB profile
    QFontDatabase: Cannot find font directory /home/vagrant/dev/Coati_External/Linux-x86_64/centos/Release/qt/lib/fonts - is Qt installed correctly?
```

OS: Linux with KDE 5.6.4, Qt 5.6

**Comment by egraether** [comment]
@dukebarman We are trying to reproduce. It looks like part of the window is cut off.

Are you using a system wide GUI zoom or font zoom? Are you using a highDPI monitor?

**Comment by dukebarman** [comment]
Nope.

It's a problem on different monitors. My linux works in Virtual Env (VMWare with installed vmware-tools) with full screen and not. Maybe it will be fixed in new version (https://github.com/CoatiSoftware/CoatiBugTracker/issues/92)?

**Comment by mlangkabel** [comment]
@dukebarman good news! We have released Coati 0.7 yesterday. This release includes a workaround for your problem. Even though we have not been able to reproduce, it seems like Coati is not able to resize any overlay windows on your system once they are created. 
Thus we added a settings option to override the initial size of these windows. To fix it on your system open the `ApplicationSettings` file located in Coati's [data folder](https://www.coati.io/documentation/#Datafolder) and add/change the following tags:
```
<config>
   <application>
      <window_base_width>600</window_base_width>
      <window_base_height>600</window_base_height>
   </application>
</config>
```
This should provide enough space for the start screen. It is just a hotfix and we aim to solve this thoroughly in the future.

**Comment by dukebarman** [comment]
I see buttons :) but with black part again:

Standard settings:
![2016-06-29_14-56-11](https://cloud.githubusercontent.com/assets/1186777/16455990/fa098b5e-3e1e-11e6-8272-bd0aad2f4a2e.png)


Change `ApplicationSettings`:
![2016-06-29_17-25-09](https://cloud.githubusercontent.com/assets/1186777/16455976/e67754fe-3e1e-11e6-9903-9e187523d3c7.png)

**Comment by st4ll1** [comment]
@dukebarman
We are aware of this problem. It appears on some Linux installations.
The black parts are should be transparent.
 Normally it can be solved to configure your composite manager for transparency.

**Comment by mlangkabel** [comment]
Additional windows now have a resize grip in the lower right corner. This should fix the problem once and for all :)
